'use strict'

const enumValidation = require('../../app/constants/enum-validation');

const SANITATION = [
    { bodyName: 'nik', validationType: enumValidation.IS_LENGTH, min: 16, max: 16, regex: '' },
    { bodyName: 'nama', validationType: enumValidation.IS_LENGTH, min: 1, max: 200, regex: '' },
    { bodyName: 'tempat_lahir', validationType: enumValidation.IS_LENGTH, min: 1, max: 80, regex: '' },
    { bodyName: 'tanggal_lahir', validationType: enumValidation.IS_DATE, regex: '' },
    { bodyName: 'jenis_kelamin', validationType: enumValidation.IS_LENGTH, min: 1, max: 1, regex: '' },
    { bodyName: 'nama_ibu_kandung', validationType: enumValidation.IS_LENGTH, min: 1, max: 200, regex: '' },
    { bodyName: 'agama_id', validationType: enumValidation.IS_NUMERIC, regex: '' },
    { bodyName: 'kebutuhan_khusus_id', validationType: enumValidation.IS_NUMERIC, regex: '' },
    { bodyName: 'status_perkawinan', validationType: enumValidation.IS_NUMERIC, regex: '' },
    { bodyName: 'email', validationType: enumValidation.IS_EMAIL, min: 5, max: 60, regex: '' },
    { bodyName: 'kewarganegaraan', validationType: enumValidation.IS_LENGTH, min: 2, max: 2, regex: '' },
    { bodyName: 'kode_wilayah', validationType: enumValidation.IS_LENGTH, min: 8, max: 8, regex: '' },
    { bodyName: 'alamat_jalan', validationType: enumValidation.IS_LENGTH, min: 1, max: 255, regex: '' },
    { bodyName: 'rt', validationType: enumValidation.IS_NUMERIC, regex: '' },
    { bodyName: 'rw', validationType: enumValidation.IS_NUMERIC, regex: '' },
    { bodyName: 'desa_kelurahan', validationType: enumValidation.IS_LENGTH, min: 1, max: 60, regex: '' },
    { bodyName: 'kode_pos', validationType: enumValidation.IS_LENGTH, min: 5, max: 5, regex: '' },
    { bodyName: 'jenis_ptk_id', validationType: enumValidation.IS_NUMERIC, regex: '' },
    { bodyName: 'jabatan_ptk_id', validationType: enumValidation.IS_NUMERIC, regex: '' },
    { bodyName: 'status_kepegawaian_id', validationType: enumValidation.IS_NUMERIC, regex: '' },
    { bodyName: 'nip', validationType: enumValidation.IS_LENGTH, min: 0, max: 18, regex: '' },
    { bodyName: 'lembaga_pengangkat_id', validationType: enumValidation.IS_NUMERIC, regex: '' },
    { bodyName: 'sk_pengangkatan', validationType: enumValidation.IS_LENGTH, min: 1, max: 80, regex: '' },
    { bodyName: 'tmt_pengangkatan', validationType: enumValidation.IS_DATE, regex: '' },
    { bodyName: 'sumber_gaji_id', validationType: enumValidation.IS_NUMERIC, regex: '' },
    { bodyName: 'sudah_lisensi_kepala_sekolah', validationType: enumValidation.IS_NUMERIC, regex: '' },
    { bodyName: 'nomor_surat_tugas', validationType: enumValidation.IS_LENGTH, min: 1, max: 50, regex: '' },
    { bodyName: 'tgl_surat_tugas', validationType: enumValidation.IS_DATE, regex: '' },
    { bodyName: 'tmt_tugas', validationType: enumValidation.IS_DATE, regex: '' },
    { bodyName: 'status_keaktifan_id', validationType: enumValidation.IS_NUMERIC, regex: '' },
    { bodyName: 'pekerjaan_suami_istri', validationType: enumValidation.IS_NUMERIC, regex: '' },
    { bodyName: 'soft_delete', validationType: enumValidation.IS_NUMERIC, regex: '' },
    { bodyName: 'jenis_keluar_id', validationType: enumValidation.IS_NUMERIC, regex: '' },
    { bodyName: 'tgl_ptk_keluar', validationType: enumValidation.IS_DATE, regex: '' },
    { bodyName: 'ptk_induk', validationType: enumValidation.IS_NUMERIC, regex: '' },
    { bodyName: 'aktif_bulan_01', validationType: enumValidation.IS_NUMERIC, regex: '' },
    { bodyName: 'aktif_bulan_02', validationType: enumValidation.IS_NUMERIC, regex: '' },
    { bodyName: 'aktif_bulan_03', validationType: enumValidation.IS_NUMERIC, regex: '' },
    { bodyName: 'aktif_bulan_04', validationType: enumValidation.IS_NUMERIC, regex: '' },
    { bodyName: 'aktif_bulan_05', validationType: enumValidation.IS_NUMERIC, regex: '' },
    { bodyName: 'aktif_bulan_06', validationType: enumValidation.IS_NUMERIC, regex: '' },
    { bodyName: 'aktif_bulan_07', validationType: enumValidation.IS_NUMERIC, regex: '' },
    { bodyName: 'aktif_bulan_08', validationType: enumValidation.IS_NUMERIC, regex: '' },
    { bodyName: 'aktif_bulan_09', validationType: enumValidation.IS_NUMERIC, regex: '' },
    { bodyName: 'aktif_bulan_10', validationType: enumValidation.IS_NUMERIC, regex: '' },
    { bodyName: 'aktif_bulan_11', validationType: enumValidation.IS_NUMERIC, regex: '' },
    { bodyName: 'aktif_bulan_12', validationType: enumValidation.IS_NUMERIC, regex: '' },
    { bodyName: 'status_approval', validationType: enumValidation.IS_NUMERIC, regex: '' },
    { bodyName: 'approval_date', validationType: enumValidation.IS_DATE, regex: '' },
    { bodyName: 'keterangan', validationType: enumValidation.IS_LENGTH, min: 1, max: 250, regex: '' },
];

module.exports = SANITATION;
